# Generated by Django 5.0 on 2026-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Size, Color, Weight', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name (optional)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.productattribute')),
            ],
            options={
                'verbose_name_plural': 'Product Attribute Values',
                'ordering': ['attribute', 'display_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (optional)', max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Variant specific price', max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Sale price for this variant', max_digits=10)),
                ('is_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Variant specific image', null=True, upload_to='product/variants/')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock for this variant')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_values', models.ManyToManyField(blank=True, related_name='variants', to='product.productattributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'sku'],
            },
        ),
    ]
