# Generated by Django 5.0 on 2024-08-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_orderitem_subtotal_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price',
        ),
    ]
